package com.espressho.mokapot;

import javacard.framework.*;
import javacard.security.*;
import javacardx.crypto.*;

/**
 * SSHKeyApplet — Mokapot JavaCard applet.
 *
 * Stores up to 4 EC P-256 keypairs in EEPROM and exposes them for SSH signing
 * via the APDU interface described in CLAUDE.md and doc/APDU-Protocol-Specification.md.
 *
 * AID:
 *   Package : CA FE 4D 6F 6B 61        (6 bytes, "CafeMok[a]")
 *   Applet  : CA FE 4D 6F 6B 61 00 01 00 00 00 00 00 00 00 00 (16 bytes)
 *
 * ## Card lifecycle
 *
 * After installation the card is **uninitialized**.  Only SELECT and
 * INS_CARD_INIT (0xA0) are accepted.  Every other instruction returns
 * SW_SECURITY_STATUS_NOT_SATISFIED (0x6982) until CARD_INIT has been called.
 *
 * CARD_INIT sets the PIN and PUK and flips the persistent `initialized` flag.
 * From that point the full instruction set is available.
 *
 * INS_RESET_CARD (0xA4) is a two-phase nuclear reset that returns the card to
 * the uninitialized state without requiring any credentials.  It is the escape
 * hatch for "I locked myself out and/or need to hand the card to someone else."
 *
 * ## Security model
 *
 * Read operations (GET_PUBKEY, LIST_KEYS, GET_FLAGS): no PIN required.
 * Write operations (GEN_KEY, REGEN_KEY, CLEAR_KEY): PIN embedded in APDU.
 * Admin operations (SET_PIN, SET_PUK, UNBLOCK_CARD): require respective secret.
 * RESET_CARD: two-phase nonce only — no credentials needed.
 *
 * All signing is performed on-card; private key material never leaves the card.
 * The host only ever receives DER-encoded ECDSA signatures and raw public keys.
 *
 * ## PIN notes
 *
 * - No default PIN/PUK — credentials are set by INS_CARD_INIT.
 * - Max PIN tries: 3 — card blocks on exhaustion; PUK or RESET required.
 * - Max PUK tries: 5 — PUK permanently blocks if exhausted; RESET required.
 * - PIN session state resets on deselect / power-off (OwnerPIN semantics).
 * - Timeout enforcement (FLAG_TIMEOUT) is the host's responsibility; the card
 *   only tracks whether the PIN has been verified this session.
 */
public class SSHKeyApplet extends Applet {

    // =========================================================================
    // Limits
    // =========================================================================

    private static final byte MAX_KEYS = (byte) 4;
    private static final byte PIN_MAX_TRIES = (byte) 3;
    private static final byte PUK_MAX_TRIES = (byte) 5;
    private static final byte PIN_MAX_LEN = (byte) 8;
    private static final byte PUK_MAX_LEN = (byte) 8;
    private static final short PUBKEY_LEN = (short) 65;
    /** Length of the factory-reset confirmation nonce in bytes. */
    private static final short RESET_NONCE_LEN = (short) 16;

    // =========================================================================
    // Persistent state (EEPROM — survives power-off)
    // =========================================================================

    /** Up to 4 keypairs.  Null slot = empty. */
    private KeyPair[] keyPairs;

    /** Per-slot flag byte (see APDUConstants.FLAG_*). */
    private byte[] keyFlags;

    /** Card PIN — validated once per session (resets on deselect). */
    private OwnerPIN pin;

    /** PUK — used only to unblock a blocked PIN. */
    private OwnerPIN puk;

    /**
     * Whether INS_CARD_INIT has been called.  All instructions except SELECT
     * and INS_CARD_INIT are gated behind this flag.  Persists across power
     * cycles; cleared only by a successful INS_RESET_CARD.
     */
    private boolean initialized;

    // =========================================================================
    // Transient state (CLEAR_ON_DESELECT — wiped on card deselect/power-off)
    // =========================================================================

    /**
     * Scratch buffer for public key export.  Transient so a public key value
     * is never accidentally retained across sessions in RAM.
     */
    private byte[] pubKeyScratch;

    /**
     * Pending factory-reset nonce.  Generated by Phase 1 of INS_RESET_CARD and
     * consumed (or invalidated) by Phase 2.  CLEAR_ON_DESELECT zeroes this on
     * deselect, which also serves as the "no nonce pending" sentinel — a fully
     * zeroed array means no Phase 1 has been issued this session.
     */
    private byte[] resetNonce;

    // =========================================================================
    // Shared crypto instances (allocated once, reused)
    // =========================================================================

    /**
     * ALG_ECDSA_SHA_256 with signPreComputedHash(): the host pre-computes the
     * hash and the card signs the digest directly without internal re-hashing.
     */
    private Signature signer;

    /** Secure random number generator — used for factory-reset nonce. */
    private RandomData rng;

    // =========================================================================
    // Constructor / install
    // =========================================================================

    // In this case, we don't care about the escale chance -- we're never going to be subclassed
    @java.lang.SuppressWarnings({ "all", "this-escape" })
    protected SSHKeyApplet() {
        // PIN and PUK objects must be allocated at install time (EEPROM slots).
        // Credentials are NOT set here — they are established by INS_CARD_INIT.
        pin = new OwnerPIN(PIN_MAX_TRIES, PIN_MAX_LEN);
        puk = new OwnerPIN(PUK_MAX_TRIES, PUK_MAX_LEN);

        keyPairs = new KeyPair[MAX_KEYS];
        keyFlags = new byte[MAX_KEYS];

        // initialized defaults to false (EEPROM boolean zero-initialisation).

        signer = Signature.getInstance(Signature.ALG_ECDSA_SHA_256, false);
        rng = RandomData.getInstance(RandomData.ALG_TRNG);

        pubKeyScratch = JCSystem.makeTransientByteArray(
            PUBKEY_LEN,
            JCSystem.CLEAR_ON_DESELECT
        );
        resetNonce = JCSystem.makeTransientByteArray(
            RESET_NONCE_LEN,
            JCSystem.CLEAR_ON_DESELECT
        );

        register();
    }

    public static void install(byte[] bArray, short bOffset, byte bLength) {
        new SSHKeyApplet();
    }

    // =========================================================================
    // APDU dispatch
    // =========================================================================

    public void process(APDU apdu) throws ISOException {
        // The framework handles SELECT before reaching here.
        if (selectingApplet()) {
            return;
        }

        byte[] buf = apdu.getBuffer();

        if (buf[ISO7816.OFFSET_CLA] != (byte) 0x00) {
            ISOException.throwIt(ISO7816.SW_CLA_NOT_SUPPORTED);
        }

        byte ins = buf[ISO7816.OFFSET_INS];

        // Gate: every instruction except INS_CARD_INIT requires initialization.
        // An uninitialized card only accepts SELECT (handled above) and CARD_INIT.
        if (!initialized && ins != APDUConstants.INS_CARD_INIT) {
            ISOException.throwIt(ISO7816.SW_COMMAND_NOT_ALLOWED);
        }

        switch (ins) {
            case APDUConstants.INS_GEN_KEY:
                handleGenKey(apdu);
                break;
            case APDUConstants.INS_GET_PUBKEY:
                handleGetPubKey(apdu);
                break;
            case APDUConstants.INS_SIGN:
                handleSign(apdu);
                break;
            case APDUConstants.INS_LIST_KEYS:
                handleListKeys(apdu);
                break;
            case APDUConstants.INS_VERIFY_PIN:
                handleVerifyPIN(apdu);
                break;
            case APDUConstants.INS_REGEN_KEY:
                handleRegenKey(apdu);
                break;
            case APDUConstants.INS_CLEAR_KEY:
                handleClearKey(apdu);
                break;
            case APDUConstants.INS_GET_FLAGS:
                handleGetFlags(apdu);
                break;
            // Admin block -------------------------------------------------------
            case APDUConstants.INS_CARD_INIT:
                handleCardInit(apdu);
                break;
            case APDUConstants.INS_SET_PIN:
                handleSetPIN(apdu);
                break;
            case APDUConstants.INS_SET_PUK:
                handleSetPUK(apdu);
                break;
            case APDUConstants.INS_UNBLOCK_CARD:
                handleUnblockCard(apdu);
                break;
            case APDUConstants.INS_RESET_CARD:
                handleResetCard(apdu);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }

    // =========================================================================
    // Normal instruction handlers (0x01–0x08)
    // =========================================================================

    /**
     * INS_GEN_KEY (0x01) — generate a new keypair in the specified slot.
     *
     * APDU format: [PIN_LEN][PIN][FLAGS]
     * P1 = slot (0–3), P2 = reserved (0x00).
     *
     * Fails with SW_KEY_EXISTS if the slot is already occupied; use
     * INS_REGEN_KEY to replace an existing key.
     *
     * Returns the 65-byte uncompressed public key on success.
     */
    private void handleGenKey(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte slot = buf[ISO7816.OFFSET_P1];
        checkSlot(slot);

        short dataLen = apdu.setIncomingAndReceive();
        if (dataLen < 2) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        byte pinLen = buf[ISO7816.OFFSET_CDATA];
        if (pinLen < 1 || pinLen > PIN_MAX_LEN) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        if (dataLen != (short) (1 + pinLen + 1)) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        if (!pin.check(buf, (short) (ISO7816.OFFSET_CDATA + 1), pinLen)) {
            ISOException.throwIt(
                APDUConstants.SW_SECURITY_STATUS_NOT_SATISFIED
            );
        }

        // Refuse to silently overwrite an existing key.
        try {
            if (
                keyPairs[slot] != null &&
                keyPairs[slot].getPrivate() != null &&
                keyPairs[slot].getPrivate().isInitialized()
            ) {
                ISOException.throwIt(APDUConstants.SW_KEY_EXISTS);
            }
        } catch (ISOException iso) {
            throw iso;
        } catch (Exception e) {
            // Treat any other exception as "not initialized" — defensive.
        }

        byte flags = buf[ISO7816.OFFSET_CDATA + 1 + pinLen];
        validateFlags(flags);

        KeyPair kp = makeP256KeyPair();
        keyPairs[slot] = kp;
        keyFlags[slot] = flags;

        returnUncompressedPublicKey(apdu, kp);
    }

    /**
     * INS_GET_PUBKEY (0x02) — return the 65-byte uncompressed public key for a slot.
     * P1 = slot (0–3).  No PIN required.
     */
    private void handleGetPubKey(APDU apdu) {
        byte slot = apdu.getBuffer()[ISO7816.OFFSET_P1];
        checkSlot(slot);
        checkKeyPresent(slot);

        ECPublicKey pubKey = (ECPublicKey) keyPairs[slot].getPublic();
        short keyLen = pubKey.getW(pubKeyScratch, (short) 0);

        apdu.setOutgoing();
        apdu.setOutgoingLength(keyLen);
        apdu.sendBytesLong(pubKeyScratch, (short) 0, keyLen);
    }

    /**
     * INS_SIGN (0x03) — sign a pre-computed hash with the key in a slot.
     *
     * P1 = slot (0–3)
     * P2 = flags (FLAG_REQUIRE_PIN forces re-validation regardless of slot flags)
     * Data = pre-computed hash digest (1–128 bytes; typically 32 for SHA-256)
     * Response = DER-encoded ECDSA signature (max 72 bytes for P-256)
     *
     * The host is responsible for hashing.  The card calls
     * signPreComputedHash() — NO internal hashing occurs.
     */
    private void handleSign(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte slot = buf[ISO7816.OFFSET_P1];
        byte flags = buf[ISO7816.OFFSET_P2];
        checkSlot(slot);
        checkKeyPresent(slot);

        boolean requirePIN =
            ((keyFlags[slot] | flags) & APDUConstants.FLAG_REQUIRE_PIN) != 0;
        if (requirePIN && !pin.isValidated()) {
            ISOException.throwIt(ISO7816.SW_SECURITY_STATUS_NOT_SATISFIED);
        }

        short digestLen = apdu.setIncomingAndReceive();
        // signPreComputedHash() accepts any digest length; 128 bytes is a
        // generous upper bound covering SHA-512 and similar outputs.
        if (digestLen < (short) 1 || digestLen > (short) 128) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        ECPrivateKey privKey = (ECPrivateKey) keyPairs[slot].getPrivate();
        signer.init(privKey, Signature.MODE_SIGN);
        short sigLen = signer.signPreComputedHash(
            buf,
            ISO7816.OFFSET_CDATA,
            digestLen,
            buf,
            (short) 0
        );

        apdu.setOutgoing();
        apdu.setOutgoingLength(sigLen);
        apdu.sendBytes((short) 0, sigLen);
    }

    /**
     * INS_LIST_KEYS (0x04) — return a 1-byte bitmask of populated slots.
     * Bit N is set if slot N contains an initialized key.  No PIN required.
     */
    private void handleListKeys(APDU apdu) {
        byte mask = 0;
        for (byte i = 0; i < MAX_KEYS; i++) {
            if (
                keyPairs[i] != null && keyPairs[i].getPrivate().isInitialized()
            ) {
                mask |= (byte) (1 << i);
            }
        }
        byte[] buf = apdu.getBuffer();
        buf[0] = mask;
        apdu.setOutgoing();
        apdu.setOutgoingLength((short) 1);
        apdu.sendBytes((short) 0, (short) 1);
    }

    /**
     * INS_VERIFY_PIN (0x05) — verify the card PIN for this session.
     * Data = PIN bytes.
     *
     * Returns 0x63Cx (x = tries remaining) on failure, 0x6983 if blocked.
     * On exhaustion triggers FLAG_ERASE_ON_LOCK for all eligible slots.
     */
    private void handleVerifyPIN(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        short dataLen = apdu.setIncomingAndReceive();

        if (pin.getTriesRemaining() == 0) {
            ISOException.throwIt(APDUConstants.SW_PIN_BLOCKED);
        }

        if (!pin.check(buf, ISO7816.OFFSET_CDATA, (byte) dataLen)) {
            if (pin.getTriesRemaining() == 0) {
                eraseLockedKeys();
                ISOException.throwIt(APDUConstants.SW_PIN_BLOCKED);
            }
            ISOException.throwIt(
                (short) (APDUConstants.SW_WRONG_PIN_BASE |
                    pin.getTriesRemaining())
            );
        }
        // Success — SW 9000 sent automatically.
    }

    /**
     * INS_REGEN_KEY (0x06) — regenerate (replace) the keypair in a slot.
     *
     * APDU format: [PIN_LEN][PIN][FLAGS]
     * P1 = slot (0–3), P2 = reserved (0x00).
     * Response = new 65-byte uncompressed public key.
     *
     * Replaces any existing key without an occupancy check.
     * Flags are set explicitly from the APDU; previous flags are NOT preserved.
     */
    private void handleRegenKey(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte slot = buf[ISO7816.OFFSET_P1];
        checkSlot(slot);

        short dataLen = apdu.setIncomingAndReceive();
        if (dataLen < 2) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        byte pinLen = buf[ISO7816.OFFSET_CDATA];
        if (pinLen < 1 || pinLen > PIN_MAX_LEN) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        if (dataLen != (short) (1 + pinLen + 1)) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        if (!pin.check(buf, (short) (ISO7816.OFFSET_CDATA + 1), pinLen)) {
            ISOException.throwIt(
                APDUConstants.SW_SECURITY_STATUS_NOT_SATISFIED
            );
        }

        byte flags = buf[ISO7816.OFFSET_CDATA + 1 + pinLen];
        validateFlags(flags);

        JCSystem.beginTransaction();
        try {
            KeyPair kp = makeP256KeyPair();
            keyPairs[slot] = kp;
            keyFlags[slot] = flags;
            JCSystem.commitTransaction();
        } catch (ISOException iso) {
            JCSystem.abortTransaction();
            throw iso;
        } catch (Exception e) {
            JCSystem.abortTransaction();
            ISOException.throwIt(ISO7816.SW_UNKNOWN);
        }

        returnUncompressedPublicKey(apdu, keyPairs[slot]);
    }

    /**
     * INS_CLEAR_KEY (0x07) — securely delete a keypair from a slot.
     *
     * APDU format: [PIN_LEN][PIN][FLAGS]
     * P1 = slot (0–3), P2 = reserved (0x00).
     * FLAGS field must be valid (reserved bits zero) but its value is ignored.
     * Safe to call on an empty slot.
     */
    private void handleClearKey(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte slot = buf[ISO7816.OFFSET_P1];
        checkSlot(slot);

        short dataLen = apdu.setIncomingAndReceive();
        if (dataLen < 2) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        byte pinLen = buf[ISO7816.OFFSET_CDATA];
        if (pinLen < 1 || pinLen > PIN_MAX_LEN) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        if (dataLen != (short) (1 + pinLen + 1)) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        if (!pin.check(buf, (short) (ISO7816.OFFSET_CDATA + 1), pinLen)) {
            ISOException.throwIt(
                APDUConstants.SW_SECURITY_STATUS_NOT_SATISFIED
            );
        }

        // FLAGS must be valid even though ignored, to keep the format honest.
        byte flags = buf[ISO7816.OFFSET_CDATA + 1 + pinLen];
        validateFlags(flags);

        JCSystem.beginTransaction();
        try {
            if (keyPairs[slot] != null) {
                keyPairs[slot].getPrivate().clearKey();
                keyPairs[slot].getPublic().clearKey();
                keyPairs[slot] = null;
            }
            keyFlags[slot] = 0;
            JCSystem.commitTransaction();
        } catch (ISOException iso) {
            JCSystem.abortTransaction();
            throw iso;
        } catch (Exception e) {
            JCSystem.abortTransaction();
            ISOException.throwIt(ISO7816.SW_UNKNOWN);
        }
    }

    /**
     * INS_GET_FLAGS (0x08) — return the flags byte for a slot.
     * P1 = slot (0–3).  No PIN required (read-only).
     * Response = 1-byte flags value.
     */
    private void handleGetFlags(APDU apdu) {
        byte slot = apdu.getBuffer()[ISO7816.OFFSET_P1];
        checkSlot(slot);
        checkKeyPresent(slot);

        byte[] buf = apdu.getBuffer();
        buf[0] = keyFlags[slot];
        apdu.setOutgoing();
        apdu.setOutgoingLength((short) 1);
        apdu.sendBytes((short) 0, (short) 1);
    }

    // =========================================================================
    // Admin instruction handlers (0xA0–0xA4)
    // =========================================================================

    /**
     * INS_CARD_INIT (0xA0) — one-time card initialization.
     *
     * Sets the PIN and PUK and marks the card as initialized.  This is the
     * only instruction (besides SELECT) that works on an uninitialized card.
     * Calling it on an already-initialized card returns
     * SW_SECURITY_STATUS_NOT_SATISFIED.
     *
     * APDU format:
     *   P1 = PIN length (1–8)
     *   P2 = PUK length (1–8)
     *   Data = [PIN bytes] || [PUK bytes]
     */
    private void handleCardInit(APDU apdu) {
        if (initialized) {
            // Re-initialization is not permitted.
            ISOException.throwIt(
                APDUConstants.SW_SECURITY_STATUS_NOT_SATISFIED
            );
        }

        byte[] buf = apdu.getBuffer();
        byte pinLen = buf[ISO7816.OFFSET_P1];
        byte pukLen = buf[ISO7816.OFFSET_P2];

        if (pinLen < 1 || pinLen > PIN_MAX_LEN) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }
        if (pukLen < 1 || pukLen > PUK_MAX_LEN) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        short dataLen = apdu.setIncomingAndReceive();
        if (dataLen != (short) (pinLen + pukLen)) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        // Atomically set both credentials and flip the initialized flag.
        JCSystem.beginTransaction();
        try {
            pin.update(buf, ISO7816.OFFSET_CDATA, pinLen);
            puk.update(buf, (short) (ISO7816.OFFSET_CDATA + pinLen), pukLen);
            initialized = true;
            JCSystem.commitTransaction();
        } catch (ISOException iso) {
            JCSystem.abortTransaction();
            throw iso;
        } catch (Exception e) {
            JCSystem.abortTransaction();
            ISOException.throwIt(ISO7816.SW_UNKNOWN);
        }
        // Success — SW 9000 sent automatically.
    }

    /**
     * INS_SET_PIN (0xA1) — change the card PIN.
     *
     * P1 = old PIN length.
     * Data = [old PIN bytes] || [new PIN bytes].
     *
     * Does not require a prior INS_VERIFY_PIN — the old PIN is verified inline.
     * On exhaustion of tries, triggers FLAG_ERASE_ON_LOCK for eligible slots.
     */
    private void handleSetPIN(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte oldPINLen = buf[ISO7816.OFFSET_P1];
        short totalLen = apdu.setIncomingAndReceive();

        if (oldPINLen <= 0 || oldPINLen >= totalLen) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        short newPINOffset = (short) (ISO7816.OFFSET_CDATA + oldPINLen);
        byte newPINLen = (byte) (totalLen - oldPINLen);

        if (pin.getTriesRemaining() == 0) {
            ISOException.throwIt(APDUConstants.SW_PIN_BLOCKED);
        }

        if (!pin.check(buf, ISO7816.OFFSET_CDATA, oldPINLen)) {
            if (pin.getTriesRemaining() == 0) {
                eraseLockedKeys();
                ISOException.throwIt(APDUConstants.SW_PIN_BLOCKED);
            }
            ISOException.throwIt(
                (short) (APDUConstants.SW_WRONG_PIN_BASE |
                    pin.getTriesRemaining())
            );
        }

        JCSystem.beginTransaction();
        try {
            pin.update(buf, newPINOffset, newPINLen);
            JCSystem.commitTransaction();
        } catch (Exception e) {
            JCSystem.abortTransaction();
            throw e;
        }
        // Success — SW 9000 sent automatically.
    }

    /**
     * INS_SET_PUK (0xA2) — change the card PUK.
     *
     * P1 = old PUK length.
     * Data = [old PUK bytes] || [new PUK bytes].
     *
     * Requires the current PUK.  If the PUK try counter is exhausted the
     * only recovery is INS_RESET_CARD.
     */
    private void handleSetPUK(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte oldPUKLen = buf[ISO7816.OFFSET_P1];
        short totalLen = apdu.setIncomingAndReceive();

        if (oldPUKLen <= 0 || oldPUKLen >= totalLen) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        short newPUKOffset = (short) (ISO7816.OFFSET_CDATA + oldPUKLen);
        byte newPUKLen = (byte) (totalLen - oldPUKLen);

        if (puk.getTriesRemaining() == 0) {
            // PUK is permanently blocked — only RESET_CARD can recover from this.
            ISOException.throwIt(APDUConstants.SW_PIN_BLOCKED);
        }

        if (!puk.check(buf, ISO7816.OFFSET_CDATA, oldPUKLen)) {
            ISOException.throwIt(
                (short) (APDUConstants.SW_WRONG_PIN_BASE |
                    puk.getTriesRemaining())
            );
        }

        JCSystem.beginTransaction();
        try {
            puk.update(buf, newPUKOffset, newPUKLen);
            JCSystem.commitTransaction();
        } catch (Exception e) {
            JCSystem.abortTransaction();
            throw e;
        }
        // Success — SW 9000 sent automatically.
    }

    /**
     * INS_UNBLOCK_CARD (0xA3) — unblock a blocked PIN using the PUK.
     *
     * P1 = PUK length in bytes.
     * Data = [PUK bytes] || [new PIN bytes].
     *
     * Resets the PIN try counter and sets the new PIN value.
     * If the PUK itself is blocked (tries exhausted), returns SW_PIN_BLOCKED;
     * the only recovery at that point is INS_RESET_CARD.
     */
    private void handleUnblockCard(APDU apdu) {
        byte[] buf = apdu.getBuffer();
        byte pukLen = buf[ISO7816.OFFSET_P1];
        short totalLen = apdu.setIncomingAndReceive();

        if (pukLen <= 0 || pukLen >= totalLen) {
            ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
        }

        short newPINOffset = (short) (ISO7816.OFFSET_CDATA + pukLen);
        byte newPINLen = (byte) (totalLen - pukLen);

        if (puk.getTriesRemaining() == 0) {
            ISOException.throwIt(APDUConstants.SW_PIN_BLOCKED);
        }

        if (!puk.check(buf, ISO7816.OFFSET_CDATA, pukLen)) {
            ISOException.throwIt(
                (short) (APDUConstants.SW_WRONG_PIN_BASE |
                    puk.getTriesRemaining())
            );
        }

        JCSystem.beginTransaction();
        try {
            pin.resetAndUnblock();
            pin.update(buf, newPINOffset, newPINLen);
            JCSystem.commitTransaction();
        } catch (Exception e) {
            JCSystem.abortTransaction();
            throw e;
        }
        // Success — SW 9000 sent automatically.
    }

    /**
     * INS_RESET_CARD (0xA4) — factory reset, two-phase.
     *
     * This is the "I forgot everything, blow it all away" escape hatch.
     * No credentials are required.  The two-phase nonce design prevents
     * accidental resets from a single malformed or replayed APDU.
     *
     * **Phase 1** — no data (resetNonce is all zeros):
     *   Generates a 16-byte cryptographic nonce, stores it in transient memory
     *   (CLEAR_ON_DESELECT), and returns it to the caller.  Deselecting the
     *   card before Phase 2 clears the nonce — start over.
     *
     * **Phase 2** — Data = 16-byte nonce (resetNonce is non-zero):
     *   Verifies the nonce with a constant-time comparison.
     *   - Match: atomically erases all key material, resets PIN/PUK counters,
     *     and sets initialized = false.
     *   - Mismatch: immediately invalidates the nonce and returns
     *     SW_SECURITY_STATUS_NOT_SATISFIED.  No retries without a new Phase 1.
     */
    private void handleResetCard(APDU apdu) {
        if (isResetNonceClear()) {
            // Phase 1: generate and return a fresh nonce.
            rng.nextBytes(resetNonce, (short) 0, RESET_NONCE_LEN);

            apdu.setOutgoing();
            apdu.setOutgoingLength(RESET_NONCE_LEN);
            apdu.sendBytesLong(resetNonce, (short) 0, RESET_NONCE_LEN);
        } else {
            // Phase 2: verify nonce and, on success, wipe everything.
            byte[] buf = apdu.getBuffer();
            short dataLen = apdu.setIncomingAndReceive();

            if (dataLen != RESET_NONCE_LEN) {
                // Wrong length — zero nonce immediately, no retries.
                Util.arrayFillNonAtomic(
                    resetNonce,
                    (short) 0,
                    RESET_NONCE_LEN,
                    (byte) 0
                );
                ISOException.throwIt(ISO7816.SW_WRONG_LENGTH);
            }

            // Util.arrayCompare is constant-time on compliant JC implementations.
            if (
                Util.arrayCompare(
                    buf,
                    ISO7816.OFFSET_CDATA,
                    resetNonce,
                    (short) 0,
                    RESET_NONCE_LEN
                ) !=
                0
            ) {
                // Wrong nonce — zero immediately, no retries.
                Util.arrayFillNonAtomic(
                    resetNonce,
                    (short) 0,
                    RESET_NONCE_LEN,
                    (byte) 0
                );
                ISOException.throwIt(
                    APDUConstants.SW_SECURITY_STATUS_NOT_SATISFIED
                );
            }

            // Nonce verified — zero before the slow EEPROM writes so it
            // cannot be recovered if power is lost mid-reset.
            Util.arrayFillNonAtomic(
                resetNonce,
                (short) 0,
                RESET_NONCE_LEN,
                (byte) 0
            );

            // Atomically erase all key material and reset credentials.
            JCSystem.beginTransaction();
            try {
                for (byte i = 0; i < MAX_KEYS; i++) {
                    if (keyPairs[i] != null) {
                        keyPairs[i].getPrivate().clearKey();
                        keyPairs[i].getPublic().clearKey();
                        keyPairs[i] = null;
                    }
                    keyFlags[i] = 0;
                }
                // Resets try counters and clears the "validated" session flag.
                // The PIN/PUK values themselves are now irrelevant — CARD_INIT
                // will overwrite them on next initialization.
                pin.resetAndUnblock();
                puk.resetAndUnblock();
                initialized = false;
                JCSystem.commitTransaction();
            } catch (ISOException iso) {
                JCSystem.abortTransaction();
                throw iso;
            } catch (Exception e) {
                JCSystem.abortTransaction();
                ISOException.throwIt(ISO7816.SW_UNKNOWN);
            }
            // Success — SW 9000 sent automatically.
        }
    }

    // =========================================================================
    // Private helpers
    // =========================================================================

    /**
     * Allocate and configure a fresh P-256 KeyPair with proper domain parameters.
     *
     * Uses a two-phase approach: first try the direct KeyPair constructor (most
     * implementations), then fall back to building keys individually (some older
     * implementations require curve params before genKeyPair() is called).
     */
    private KeyPair makeP256KeyPair() {
        try {
            KeyPair kp = null;

            try {
                kp = new KeyPair(
                    KeyPair.ALG_EC_FP,
                    KeyBuilder.LENGTH_EC_FP_256
                );
                ensureP256CurveInitialized(kp);
            } catch (Exception e) {
                ECPrivateKey ecPrivKey = (ECPrivateKey) KeyBuilder.buildKey(
                    KeyBuilder.TYPE_EC_FP_PRIVATE,
                    KeyBuilder.LENGTH_EC_FP_256,
                    false
                );
                ECPublicKey ecPubKey = (ECPublicKey) KeyBuilder.buildKey(
                    KeyBuilder.TYPE_EC_FP_PUBLIC,
                    KeyBuilder.LENGTH_EC_FP_256,
                    false
                );

                if (ecPrivKey != null && ecPubKey != null) {
                    setP256CurveParams(ecPubKey, ecPrivKey);
                    kp = new KeyPair(ecPubKey, ecPrivKey);
                }
            }

            if (kp != null) {
                kp.genKeyPair();
                return kp;
            } else {
                ISOException.throwIt(ISO7816.SW_CONDITIONS_NOT_SATISFIED);
            }
        } catch (CryptoException ex) {
            switch (ex.getReason()) {
                case CryptoException.ILLEGAL_USE:
                case CryptoException.NO_SUCH_ALGORITHM:
                    ISOException.throwIt(ISO7816.SW_FUNC_NOT_SUPPORTED);
                    break;
                case CryptoException.INVALID_INIT:
                    ISOException.throwIt(ISO7816.SW_CONDITIONS_NOT_SATISFIED);
                    break;
                case CryptoException.ILLEGAL_VALUE:
                    ISOException.throwIt(ISO7816.SW_DATA_INVALID);
                    break;
                default:
                    ISOException.throwIt(ISO7816.SW_UNKNOWN);
            }
        } catch (Exception e) {
            ISOException.throwIt(ISO7816.SW_UNKNOWN);
        }
        return null; // Never reached.
    }

    /** JCAlgTest-inspired curve initialization for the two-phase key build path. */
    private void ensureP256CurveInitialized(KeyPair ecKeyPair) {
        ECPublicKey ecPubKey = (ECPublicKey) ecKeyPair.getPublic();
        ECPrivateKey ecPrivKey = (ECPrivateKey) ecKeyPair.getPrivate();

        try {
            if (ecPubKey == null) {
                ecKeyPair.genKeyPair();
            }
        } catch (Exception e) {
            // Intentionally ignored — best-effort pre-init.
        }

        setP256CurveParams(ecPubKey, ecPrivKey);
    }

    /** Set NIST P-256 domain parameters on a pub/priv key pair using the JCAlgTest approach. */
    private void setP256CurveParams(ECPublicKey pubKey, ECPrivateKey privKey) {
        // Build the uncompressed generator point G = 0x04 || G_X || G_Y in a
        // local scratch buffer.  ROM constants avoid EEPROM wear.
        byte[] auxBuffer = new byte[80];
        auxBuffer[0] = 0x04;
        short off = 1;
        off = Util.arrayCopyNonAtomic(
            ECParams.P256_G_X,
            (short) 0,
            auxBuffer,
            off,
            (short) ECParams.P256_G_X.length
        );
        Util.arrayCopyNonAtomic(
            ECParams.P256_G_Y,
            (short) 0,
            auxBuffer,
            off,
            (short) ECParams.P256_G_Y.length
        );
        short gSize = (short) (1 +
            ECParams.P256_G_X.length +
            ECParams.P256_G_Y.length);

        pubKey.setFieldFP(
            ECParams.P256_P,
            (short) 0,
            (short) ECParams.P256_P.length
        );
        privKey.setFieldFP(
            ECParams.P256_P,
            (short) 0,
            (short) ECParams.P256_P.length
        );
        pubKey.setA(ECParams.P256_A, (short) 0, (short) ECParams.P256_A.length);
        privKey.setA(
            ECParams.P256_A,
            (short) 0,
            (short) ECParams.P256_A.length
        );
        pubKey.setB(ECParams.P256_B, (short) 0, (short) ECParams.P256_B.length);
        privKey.setB(
            ECParams.P256_B,
            (short) 0,
            (short) ECParams.P256_B.length
        );
        pubKey.setG(auxBuffer, (short) 0, gSize);
        privKey.setG(auxBuffer, (short) 0, gSize);
        pubKey.setR(ECParams.P256_R, (short) 0, (short) ECParams.P256_R.length);
        privKey.setR(
            ECParams.P256_R,
            (short) 0,
            (short) ECParams.P256_R.length
        );
        pubKey.setK(ECParams.P256_K);
        privKey.setK(ECParams.P256_K);
    }

    /**
     * Returns true if the reset nonce is all zeros (i.e. no Phase 1 has been
     * issued this session).  CLEAR_ON_DESELECT guarantees the array starts zeroed
     * each session; we also zero it explicitly after use or on mismatch.
     */
    private boolean isResetNonceClear() {
        for (short i = 0; i < RESET_NONCE_LEN; i++) {
            if (resetNonce[i] != 0) {
                return false;
            }
        }
        return true;
    }

    /**
     * Erase private and public key material for every slot with FLAG_ERASE_ON_LOCK.
     * Wrapped in a transaction for atomicity across potential power loss.
     * Called when the PIN try counter reaches zero.
     */
    private void eraseLockedKeys() {
        JCSystem.beginTransaction();
        try {
            for (byte i = 0; i < MAX_KEYS; i++) {
                if (
                    (keyFlags[i] & APDUConstants.FLAG_ERASE_ON_LOCK) != 0 &&
                    keyPairs[i] != null
                ) {
                    keyPairs[i].getPrivate().clearKey();
                    keyPairs[i].getPublic().clearKey();
                }
            }
            JCSystem.commitTransaction();
        } catch (Exception e) {
            JCSystem.abortTransaction();
            throw e;
        }
    }

    /**
     * Send the uncompressed public key from a KeyPair as the APDU response.
     * Used by key-generation operations to return the generated public key.
     */
    private void returnUncompressedPublicKey(APDU apdu, KeyPair keyPair) {
        ECPublicKey pubKey = (ECPublicKey) keyPair.getPublic();
        short keyLen = pubKey.getW(pubKeyScratch, (short) 0);
        apdu.setOutgoing();
        apdu.setOutgoingLength(keyLen);
        apdu.sendBytesLong(pubKeyScratch, (short) 0, keyLen);
    }

    /** Throw SW_INCORRECT_P1P2 if the slot index is out of range. */
    private void checkSlot(byte slot) {
        if (slot < 0 || slot >= MAX_KEYS) {
            ISOException.throwIt(ISO7816.SW_INCORRECT_P1P2);
        }
    }

    /** Throw SW_KEY_NOT_FOUND if the slot has no initialized private key. */
    private void checkKeyPresent(byte slot) {
        if (
            keyPairs[slot] == null ||
            !keyPairs[slot].getPrivate().isInitialized()
        ) {
            ISOException.throwIt(APDUConstants.SW_KEY_NOT_FOUND);
        }
    }

    /**
     * Validate that a flags byte has no reserved bits set.
     * Bits 2–0 are reserved; setting them is rejected to preserve
     * forward compatibility.
     */
    private void validateFlags(byte flags) {
        if ((flags & 0x07) != 0) {
            ISOException.throwIt(ISO7816.SW_WRONG_DATA);
        }
    }
}
